services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matheus-portfolio
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped